bookname: great-h-book
booktitle: すごいHiroshimaの本
language: ja
epubversion: 3
htmlversion: 5
toclevel: 2
toc: 1
aut: すごい広島
titlepage: true
rights: |
  (C) 2014-2015 すごい広島
colophon: true
urnid: http://great-h-book.eiel.info/2.0.0rc/
history:
  -
    - "2014-09-20"
  -
    - "2015-08-23"
date: "2015-08-23"
prt: すごい広島
coverimage: title.jpg
